window.ACTION_SUMMARY = {
  "sourceFile": "C:\\Users\\Sky.Lu\\Thermo Fisher Scientific\\Accounting Productivity Project - Accounting Productivity Project\\Discussion Summary.xlsx",
  "syncedAt": "2026-04-14T16:36:13",
  "items": [
    {
      "system": "VAT",
      "changePoint": "收款团队在VAT系统内直接申请开票",
      "remark": "1.  Amy强调VAT团队需要进行税务合规性判断,如品名修改是否符合税率要求\n2.  品名不能随意变更(如A改成B再改成C),需要确保税务合规\n3.  拆分也有专业要求,如不能随意拆成小数(0.8和0.2)\n4.  技术上可以给收款团队开放权限自行操作\n5.  如果收款团队接手,需要具备基本的税务和开票知识\n6.  VAT团队的专业判断包括:确认是否符合税务要求、正确的税收编码等\n7.  工作量从一个团队转移到另一个团队,整体效率提升有限",
      "fte": "0",
      "cost": "",
      "status": "取消",
      "type": "CR",
      "step": "02 开票与其他支持材料交付",
      "i": "特殊开票",
      "processStep": "特殊开票"
    },
    {
      "system": "VAT",
      "changePoint": "产品名称与官网同步",
      "remark": "1. 药监局开票品名必须和备案过的品名一致\n2. 中英文维护在中文字段\n3. 有需要去掉英文的特殊需求\n4. VAT一定要有中文名称\n5. 官网有只有英文的情况（需要看一下具体的比例）\n6. 经过数据验证，官网SKU纯中文和混合  是有中文品名能用的  加起来有 18009个物料号，占总计需要中文品名物料号（107529）的16.7%",
      "fte": "0",
      "cost": "",
      "status": "取消",
      "type": "CR",
      "step": "02 开票与其他支持材料交付",
      "i": "特殊开票",
      "processStep": "特殊开票"
    },
    {
      "system": "VAT",
      "changePoint": "发票行项目顺序调整",
      "remark": "1. 需要评估客户需求的必要性和频率\n2. 票一通系统支持此功能\n3. 还要考虑匠领系统的变更",
      "fte": "0.02",
      "cost": "100000",
      "status": "取消",
      "type": "CR",
      "step": "02 开票与其他支持材料交付",
      "i": "特殊开票",
      "processStep": "特殊开票"
    },
    {
      "system": "Credit",
      "changePoint": "Credit端增加银行水单抓取能力",
      "remark": "1.  一天多次定时同步\n2.  Share folder 去取抓AR同事手工维护的表格，进入Credit\n    - 客户抬头\n    - 金额\n    - 日期\n    - 付款摘要（备注）\n3.  需要Credit和Collection拉齐需求的理解\n补充：对于已到账未核销的款项，信控可能需要收款员确认订单明细或者用途（举例：是否可以核销超期、或者多BT的情况、或者单笔预付。）\n更新： \n1. 把现在的collection从credit审批流程里解放出来，在最后放单的时候，系统要通过邮件来通知对应的收款员即可\n2. 规范信息填写，便于Credit直接判断，无需再询问收款员",
      "fte": "0.1",
      "cost": "0",
      "status": "取消",
      "type": "CR",
      "step": "04 催收与承诺管理",
      "i": "信控合作",
      "processStep": "信控合作"
    },
    {
      "system": "Credit",
      "changePoint": "科研客户黑名单政策：从“默认解锁”评估调整为“默认锁定”",
      "remark": "1. Academia客户系统中有十万家,黑名单客户不到0.3%\n2. 维持默认解锁评估政策,不调整为默认锁定\n3. 从效率角度考虑,99.7%的客户都是良好客户,不应为极少数问题客户影响整体效率\n4. C1客户，科研类大额订单/科研类重启账户，需收款员确认经费和报账方案。",
      "fte": "0",
      "cost": "0",
      "status": "取消",
      "type": "CR",
      "step": "04 催收与承诺管理",
      "i": "信控合作",
      "processStep": "信控合作"
    },
    {
      "system": "企业微信",
      "changePoint": "使用企业微信，加第一次催收的自动化，考虑到目前约有50%的客户是可以微信沟通",
      "remark": "1. 第一层：效率提升\n减少首次催收和重复提醒的人工作业\n减少简单问题人工响应\n减少手工记录和系统更新时间\n2. 第二层：流程升级\n沟通留痕自动化\n人机协同分层处理\n从个人经验驱动转为规则驱动\n3. 第三层：管理与合规\n客户资产公司化\n过程透明\n离职交接风险降低\n数据可追踪，可分析，可审计",
      "fte": "1",
      "cost": "",
      "status": "评估中",
      "type": "New",
      "step": "04 催收与承诺管理",
      "i": "高频客户跟进",
      "processStep": "高频客户跟进"
    },
    {
      "system": "企业微信",
      "changePoint": "Enterprise WeChat + AI-Enabled Collection Automation",
      "remark": "Background\nManual first-touch collection follow-up is repetitive, time-consuming, and inconsistently traceable\nCollectors spend ~25% of their day sending routine payment reminders via email or phone or wechat\nNo centralized log of customer interactions, leading to duplicated outreach and missed follow-ups\nSolution\nDeploy Enterprise WeChat as the primary customer communication channel for collections\nIntegrate AI automation to handle: reminder triggering, interaction capture, and follow-up routing\nExample: When an invoice hits 7 days overdue, WeChat auto-sends a templated reminder; if no response within 48 hrs, the case is routed to a live agent with full conversation history\nBenefit\nReduce manual reminder volume by an estimated 30–35%, freeing collectors for complex negotiations\nImprove average first-response time from 1 days to <12 hours\nCreate structured, auditable communication records for compliance and dispute resolution",
      "fte": "1",
      "cost": "",
      "status": "评估中",
      "type": "AI",
      "step": "04 催收与承诺管理",
      "i": "高频客户跟进",
      "processStep": "高频客户跟进"
    },
    {
      "system": "Credit",
      "changePoint": "补充customer层面付款习惯信息",
      "remark": "1.  在Credit系统中新增字段,从AR Portal同步客户层面付款习惯信息\n2.  将Billing维度和客户习惯信息分开显示在两个独立表格中,便于查看\n3.  数据已在AR Portal中存在,只需增加显示字段",
      "fte": "0.01",
      "cost": "22500",
      "status": "待审批",
      "type": "CR",
      "step": "04 催收与承诺管理",
      "i": "信控合作",
      "processStep": "信控合作"
    },
    {
      "system": "Credit",
      "changePoint": "与Credit对齐收款团队跟进记录内容格式",
      "remark": "1.  增加结构化的记录格式,前面部分用下拉选项记录季度底付款预期(能付/不能付/部分支付)\n2. 后面保留详细跟进记录供收款团队使用\n3.  通过规范化格式减少团队间重复沟通,便于后续dashboard分析\n跟进格式示例：微信发送老师账单/平台确认账款，发票没有问题，已经报账，预计3-4周可以到账。写明超期原因，推动情况，按实际情况写在workflow。\n ",
      "fte": "0.09",
      "cost": "20000",
      "status": "待审批",
      "type": "CR",
      "step": "04 催收与承诺管理",
      "i": "信控合作",
      "processStep": "信控合作"
    },
    {
      "system": "Credit",
      "changePoint": "收款跟进记录实时更新至Credit解锁系统",
      "remark": "AR Portal与Credit系统同步**\n1.  当前AR portal与Credit系统每天晚上同步一次前一天数据\n2.  收款团队更新**AR Portal**后,Credit团队要等到第二天才能看到相关信息\n3.  计划调查实现实时或按需同步的可能性,减少信息延迟导致的重复询问\n实际操作中：如果credit系统显示跟进记录太多，信控同事会自己去AR Portal查看收款跟进记录（没有实时更新的必要）",
      "fte": "0",
      "cost": "0",
      "status": "取消",
      "type": "CR",
      "step": "04 催收与承诺管理",
      "i": "信控合作",
      "processStep": "信控合作"
    },
    {
      "system": "PCS",
      "changePoint": "LSG 唯一一笔（一对一/一对多）系统自动认款，无需核销员点击确认",
      "remark": "当系统只给出一个匹配方案(solution)时,准确率非常高,基本无误 。团队确认可以跳过人工确认环节,如果只有一个匹配建议且满足授权节点要求,系统可自动完成匹配 。技术上无问题,仅需确认授权流程 。",
      "fte": "0.1",
      "cost": "2500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "AI-Based Prioritization and Matching Intelligence in PCS",
      "remark": "Background\nPayment matching often depends on manual judgment, especially for customers with repeated complex patterns\nAnalysts spend ~40% of their time reviewing and correcting auto-match suggestions that lack contextual accuracy\nNo systematic way to learn from historical matching decisions, leading to repeated errors and inconsistent rule application\nSolution\nDeploy ML models trained on historical matching data to rank suggestions by confidence level and pattern recognition\nGenerate customer-specific matching rules that adapt over time based on confirmed matches and analyst corrections\nIntegrate intelligent prioritization into PCS workflow: high-confidence matches auto-apply, low-confidence items surface for review with recommended actions\nBenefit\nImprove matching accuracy by an estimated 25–35%, reducing exception volume and manual rework\nAccelerate cash application cycle time from 2–3 days to near real-time for high-confidence matches\nEnable continuous learning loop where analyst feedback progressively improves model precision and rule quality\n1.  为匹配建议添加优先级标记(HIGH/MIDDLE/LOW)\n2.  通过历史数据验证,如果HIGH优先级匹配准确率达到90-95%以上,可实现自动匹配\n3. 利用AI技术分析客户历史收款记录(半年内),总结收款逻辑并自动生成定制化匹配规则\n4.  系统可在闲暇时间(如周末)批量处理匹配逻辑生成,定期更新(每半年或2-3个月滚动更新)\n5. 优先从关键客户(经常无法一对一匹配的客户)开始实施",
      "fte": "0.3",
      "cost": "",
      "status": "评估中",
      "type": "AI",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "核销专员未认款转给收款员并生成任务",
      "remark": "1.  在系统中增加任务模块,集中显示需要收款员处理的待办事项\n2.  支持核销员或收款员之间互相cue任务,明确标记任务分配对象\n3.  解决当前虽能看到所有未核销款项,但无法快速筛选被分配任务的问题\n4.  记录任务历史,避免信息丢失,方便后续追溯\n5. 特殊场景: 包括带清账(个人代付或新建客户无BT)等没有收款员信息的款项,需要灵活分配处理",
      "fte": "0",
      "cost": "12500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "异常进账处理",
      "processStep": "异常进账处理"
    },
    {
      "system": "AR Portal",
      "changePoint": "结构化填写催收跟进记录",
      "remark": "1. 跟进记录结构化，e.g. 标签显示：客户是否承诺付款、预计付款日期等。实时对接Credit系统，便于信控同事快速阅读（节省见Credit部分）\n2. 结构化填写催收跟进记录，根据标签自动生成dashboard，展示BDQ FC、回款预测等信息",
      "fte": "1.3308775831711611E-2",
      "cost": "15000",
      "status": "待审批",
      "type": "CR",
      "step": "04 催收与承诺管理",
      "i": "付款承诺管理",
      "processStep": "付款承诺管理"
    },
    {
      "system": "AR Portal",
      "changePoint": "梳理电话催收内容并形成结构化模板/字段",
      "remark": "1. online工具、call center\n2. 企业微信的可能性\n（AI自动生成跟进记录）",
      "fte": "0.15069411203780927",
      "cost": "12500",
      "status": "待审批",
      "type": "CR",
      "step": "04 催收与承诺管理",
      "i": "付款承诺管理",
      "processStep": "付款承诺管理"
    },
    {
      "system": "AR Portal",
      "changePoint": "PIP留痕：新增邮箱需客户验证，确认邮箱被指定系统使用",
      "remark": "",
      "fte": "0",
      "cost": "5000",
      "status": "待审批",
      "type": "CR",
      "step": "03 对账与争议处理",
      "i": "对账单发送",
      "processStep": "对账单发送"
    },
    {
      "system": "AR Portal",
      "changePoint": "AR Portal发信功能/模板拓展优化",
      "remark": "",
      "fte": "0.05",
      "cost": "10000",
      "status": "待审批",
      "type": "CR",
      "step": "03 对账与争议处理",
      "i": "对账单发送",
      "processStep": "对账单发送"
    },
    {
      "system": "AR Portal",
      "changePoint": "全周期管理、自动生成对账单、跨系统取数并生成客户格式",
      "remark": "AR Portal对于全周期实现的可能性？（FTE预估仅针对call plan制定）",
      "fte": "0.06",
      "cost": "150000",
      "status": "待审批",
      "type": "CR",
      "step": "04 催收与承诺管理",
      "i": "Call Plan制定",
      "processStep": "Call Plan制定"
    },
    {
      "system": "三方平台",
      "changePoint": "锐竞平台电子章功能",
      "remark": "平台一键完下载、盖章、上传、三个功能，收费的标准按章的个数收费",
      "fte": "0.05",
      "cost": "",
      "status": "待审批",
      "type": "CR",
      "step": "02 开票与其他支持材料交付",
      "i": "其他资料交付",
      "processStep": "其他资料交付"
    },
    {
      "system": "三方平台",
      "changePoint": "RPA/自动化工具用于主要客户平台操作（金斯瑞/百望云/药明康德/三生）",
      "remark": "如果用小机器人自动匹配，能自动匹配上的大概节省工时在15H左右\n一个客户网站需要设计一套RPA流程，假设4个主要客户网站，费用主要是RPA License的费用，这里先放0",
      "fte": "5.5555555555555552E-2",
      "cost": "0",
      "status": "评估中",
      "type": "RPA",
      "step": "02 开票与其他支持材料交付",
      "i": "特殊开票",
      "processStep": "特殊开票"
    },
    {
      "system": "三方平台",
      "changePoint": "第三方客户平台供应商沟通API接口或RPA自动化方案（方圆/库巴扎/锐竞",
      "remark": "1. 方元 - 开发费2万\n2. 库巴扎 - 一次性对接费5万，日常数据服务费是销售额的0.5%。累计销售额满1000万后返2万对接费。\n3. 锐竞 - 一次性开发费\n4. 喀斯玛 - 一次性开发费\n\n如果对接能达到以下功能，预计可saving 2.6 FTE\n1）核对：根据AR表billing备注的PO或SKU/课题组，查询平台订单状态及时间。抓取返还字段：平台订单号，配送单号，收货人，收货人电话，返还至AR Portal（billing 层面）\n2）上传送货签收：库巴扎平台配送中订单上传我司送货单签收\n3）上传发票：上传发票+验真 \n4）下载：送货单/配送单，汇总结算单",
      "fte": "2.6",
      "cost": "150000",
      "status": "待审批",
      "type": "API",
      "step": "02 开票与其他支持材料交付",
      "i": "特殊开票",
      "processStep": "特殊开票"
    },
    {
      "system": "PCS",
      "changePoint": "三方代付申请完，自动流转到认款核销部分（LSG+CTC）",
      "remark": "当前三方代付审核通过后,还需要手动回到认款页面提交认款,希望实现审核通过后自动流转到认款完成   。三方代付申请时已包含所有必要信息(进账编号、金额等),系统应能自动触发认款流程 。类似功能在LSG系统也存在相同问题 。\n解决方案：\n三方代付流程与认款流程自动化优化：针对审批通过的三方代付单据，仅需根据进账信息自动完成认款，具体操作如下：\n（1）三方代付单据审批通过后，系统自动抓取对应进账核心信息（进账金额、进账单号、客户信息、关联代付单据号等）；\n（2）系统基于抓取的进账信息，自动匹配对应单据并完成认款操作，无需申请人手动发起认款及录入相关信息。\n涉及系统：LSG PCS和Non LSG  PCS",
      "fte": "0.01",
      "cost": "15000",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "第三方代付",
      "processStep": "第三方代付"
    },
    {
      "system": "MDM",
      "changePoint": "MDM增加科研客户特征字段，实现自动判断",
      "remark": "1. 校验内容\n     收票邮箱地址 \n     收票人姓名\n     收票人地址\n     收票人手机号码\n2. 科研客户的判断标准： 财务黑名单 - 这个黑名单需要有更新的能力（不管是Collection自己做还是找业务owner）\n3.  校验的对象： E1的BT对象\n4.  财务会提供一个AP portal里的已有邮箱清单，在做收票邮箱地址的时候，也要检查这个清单。（这个清单也要可维护）\n5.  把校验结果放在现有的财务审批节点，如下图的黑名单客户判定区域，增加：\n    收票邮箱地址重复检验： Yes\n    收票人姓名重复检验：No\n    收票人地址重复校验：No\n    收票人手机号码重复检验：No",
      "fte": "4.4999999999999998E-2",
      "cost": "33000",
      "status": "待审批",
      "type": "CR",
      "step": "01 准备与客户主数据",
      "i": "客户新建与主数据维护",
      "processStep": "客户新建与主数据维护"
    },
    {
      "system": "New",
      "changePoint": "AI-Assisted for Customer and Invoice Change Requests",
      "remark": "1. 联系人信息变更（BT或SO层面）\n    - 联系人邮箱\n    - 联系人电话\n    - 联系人姓名\n    - 文件接收地址\n2. 开票规则变更\n    - 暂停开票\n    - 发票类型变化\n    - 特殊开票要求更新\n        - 拆分\n        - 合并\n        - 开票时间要求\n3. 退票需求\n4. 客户开票抬头的更名（现在是通过邮件，微信直接由销售联系财务同事）：\n    - 名字\n    - 地址\n    - 银行\n    - 电话\n    \n    保证税号不变的情况下，如果有变化走新客户MDM流程\nBackground\nCustomer information changes and invoice rule updates are submitted through fragmented manual channels\nSales and collections teams spend ~20% of processing time re-keying and verifying change request data across systems\nLack of standardized intake leads to frequent handoff errors, duplicate submissions, and delayed processing\nSolution\nCreate a guided app for sales submission with structured input fields and validation rules for customer change requests\nDeploy AI-assisted extraction and classification to automatically parse change request details from unstructured inputs\nRoute classified requests to appropriate approval workflows with pre-populated data, reducing manual touchpoints\nBenefit\nImprove data input quality and first-time accuracy, reducing downstream rework by an estimated 30–40%\nReduce handoff errors between sales and collections through standardized, validated submission workflows\nAccelerate change request processing cycle from 3–5 days to <1 day for standard requests",
      "fte": "0.08",
      "cost": "100000",
      "status": "待审批",
      "type": "AI",
      "step": "01 准备与客户主数据",
      "i": "客户新建与主数据维护",
      "processStep": "客户新建与主数据维护"
    },
    {
      "system": "PCS",
      "changePoint": "押金认款和取消直接在PCS操作",
      "remark": "目前：LSG的押金是收款员在AD HOC 上做审批之后发邮件给 AR，AR在PCS做认款，然后手工Keep一个线下Excel记录。AIG有押金认款但是不能部分认款，需要有部分认款和部分转回功能。\n\n改进：copy AIG PCS，可以直接做押金认款。可以同步开发流程也可以直接把邮件作为附件上传，同时还可以保存押金协议。记录和附件都线上可查。增加部分认款。",
      "fte": "2.7777777777777779E-3",
      "cost": "",
      "status": "待报价",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "批量认款的争议和反核销需要有批量申请功能",
      "remark": "\"在认款记录里面，整合目前认款记录和批量认款记录，在此页面上进行争议\n（1）有字段可区分是单笔认款或批量认款\n（2）可勾选多笔认款点击【批量争议】进行争议\n（3）负数Billing在此模块进行争议\n（4）权限控制参考目前【认款记录】模块（核销员，操作人，认款人）\n（5）争议与清账记录进行校验；（争议记录是否要与清账记录一致才可以争议）\n（6）认款记录中的争议功能屏蔽不在使用\"\n\"对冲数据可以争议\n（1）必须勾选正负数相加为0的数据；\n（2）在同一个清账批号下的对冲数据；\n（3）对冲数据体现在认款记录中；\n对冲清账调整\n（1）原对冲数据在一共清账编号下，现在要根据组号区分分割，3个一组给RPA清账；\"\n\"争议管理重构\n（1）争议列表展示（争议总金额，认款总金额，清账总金额，争议人，争议时间等）；\n（2）争议明细显示；\n（3）争议按明细导出；\n（4）争议查询（RB，RI等）；\"\n\"争议审批\n（1）审批列表展示-针对新的争议方式，调整审批中心-待审批单据，我发起的，已审批单据，审批查询；（进账编号，客户名称，进账金额等由于批量争议数据与单笔争议不同，所以不展示）\n（2）点击列表具体记录展开查看明细审批（全部通过，全部不通过，不支持部分审批）；\n（3）争议审批明细导出；\n（4）审批后同步认款信息；\n（5）审批后同步清账信息；\"\n\"新增争议撤回\n（1）主管未审批前可撤回争议；\n（2）在争议管理里面撤回；（整批撤回，不支持部分撤回）\"",
      "fte": "3.0651340996168601E-3",
      "cost": "62500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "核销冲回",
      "processStep": "核销冲回"
    },
    {
      "system": "PCS",
      "changePoint": "批量认款模板加上Document item No.",
      "remark": "需要指定单据核销剩余固定金额，目前核销是根据一组核销相同单据号随机匹配金额",
      "fte": "3.0651340996168601E-3",
      "cost": "7500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "PO认款功能和认款建议",
      "remark": "在待认款界面认款中可通过PO勾选认款/在认款建议中可根据PO给建议",
      "fte": "0.01",
      "cost": "7500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "白名单，可供用户直接维护",
      "remark": "a. 在白名单上的客户在清账时可以豁免对于名称的校验\nb. 该页面涉及到的字段： ENTITY, 客户名称\nc. 需要引入生效时间，当设置的时间已经过期，此豁免无效\nA付款的是B的单子，如果做了映射那么A的打款只能核销B的单子，无法做双向映射，希望AB核销时不要校验",
      "fte": "0.01",
      "cost": "7500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "异常进账处理",
      "processStep": "异常进账处理"
    },
    {
      "system": "PCS",
      "changePoint": "OPEN 的VAT 报表(主要看目前哪些发票挂在账上还没付钱)",
      "remark": "报表-VAT报表中是目前是所有数据VAT，希望能筛选出来没付钱核销的VAT数据。在待认款-认款通过VAT发票池勾选未认款的发票，现在是全部都在无区分上面。",
      "fte": "0.01",
      "cost": "1500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "未清账款报告",
      "processStep": "未清账款报告"
    },
    {
      "system": "PCS",
      "changePoint": "DP差异报告",
      "remark": "报表中心-DP差异报告-COPY NON LSG，需要一个检验PCS和E1 数据一致不一致的报告",
      "fte": "0.02",
      "cost": "7500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "未清账款报告",
      "processStep": "未清账款报告"
    },
    {
      "system": "PCS",
      "changePoint": "前一天认款被清账后针对清账情况需要邮件通知认款操作员",
      "remark": "是否核销成功无提示，错误原因也无提示，只能通过查看第二天AR表判断或者等待AR同事邮件告知",
      "fte": "0.01",
      "cost": "7500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "前一天核销跳票报表",
      "remark": "看认款建议唯一一笔情况下，按照DUEDATE 排序）开发时的前提：认款建议里要区分按PCS BILLING加入的ID 顺序是否连续\n主要看跳票，目前给出的认款建议是根据金额随机提供5条内，希望系统认款建议逻辑是按照单据日期顺序排，且若识别跳票给出提示",
      "fte": "0.23",
      "cost": "10000",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "多个SO 汇总金额，多个VAT汇总，多个PO 金额等于进账金额的情况也给建议",
      "remark": "新增汇总金额匹配建议功能，当当前进账金额与以下汇总金额一致时，生成认款建议：\n（1）多个SO金额汇总后等于进账金额；\n（2）多个PO金额汇总后等于进账金额（需基于已有PO数据）。",
      "fte": "0.04",
      "cost": "12500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "所有页面带有复选框元素被勾选后需要显示具体勾选条数",
      "remark": "复选框勾选优化，所有页面中带有复选框的元素，勾选后需显示具体勾选条数，涉及模块：\n（1）本位币进账管理；\n（2）外币进账管理；\n（3）信用证进账管理；\n（4）异常进账管理；\n（5）认款建议；\n（6）待认款-认款：\n    a） Billing类型选择列表；\n    b） VAT类型选择列表。",
      "fte": "0.01",
      "cost": "5000",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "认款建议有一键展开功能",
      "remark": "认款建议增加全部勾选一键点开按钮",
      "fte": "0.01",
      "cost": "2500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "已经认过的billing做标记",
      "remark": "待认款选择billing/SO/PO/VAT类型后出来的billing是所有未清账的，需要体现出已认款标记\n已认款单据标记功能：\n（1）已认款Billing做标记；\n（2）已认款SO做标记；\n（3）已认款VAT做标记；\n（4）已认款PO做标记；\n（5）同步数据后取消标记。",
      "fte": "0.04",
      "cost": "12500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "认款建议优化（排序）",
      "remark": "新增建议逻辑\n -按照单据日期正序排序",
      "fte": "0.03",
      "cost": "2500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "RB+负数billing认款，可以认到SO，VAT和PO",
      "remark": "批量认款上传时候，只能RB对应SO/RB对应billingRB对应VAT，不能RB对应SO和billing",
      "fte": "0.01",
      "cost": "",
      "status": "待报价",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "待认款-凑数工具增强",
      "remark": "1）待认款-凑数工具里需要有用户在外部文件复制多行多列数据后可以直接在此板块粘贴后正确显示在当前 数据列表里单据号，金额，备注下的功能。\n2）要求做到再多的数据也只需粘贴一次。\n3）粘贴成功后显示在系统里的每行数据都可以进行编辑且每行在“备注”后需要有删除按钮\n4）需要有增加行的按钮\n5）需要有重置按钮可一键清除所有粘贴的内容",
      "fte": "0.02",
      "cost": "7500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "待认款页面在筛选过之后页面最下面增加汇总功能",
      "remark": "",
      "fte": "0",
      "cost": "",
      "status": "待报价",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "RI重复认款时，后一位同事提交时，需要出现提示功能",
      "remark": "新增Billing重复认款提示功能：\n（1）上传文件时，校验该Billing是否已存在认款记录；\n（2）若已存在，进一步校验该Billing的现有认款金额与本次上传的认款金额之和，与Open金额进行比较：\n      a)小于或等于Open金额则允许继续认款；\n      b)大于Open金额则提示Billing存在重复认款，不允许认款。",
      "fte": "0",
      "cost": "5000",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "报错优化",
      "remark": "新增全部校验报错提示功能，需先完成所有数据校验，再在页面展示所有错误数据。",
      "fte": "7.0000000000000007E-2",
      "cost": "2500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "认款建议优化（数量）",
      "remark": "优化建议限制，原超过5条单据不提供建议，调整为超过20条不提供建议。",
      "fte": "0",
      "cost": "2500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "PCS",
      "changePoint": "争议过的记录显示",
      "remark": "我的认款和批量认款模块，认款记录需要加争议过的记录",
      "fte": "2.7777777777777779E-3",
      "cost": "7500",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "核销冲回",
      "processStep": "核销冲回"
    },
    {
      "system": "PCS",
      "changePoint": "CODO在PCS上可操作可查询",
      "remark": "CODO（对冲数据）在PCS系统中支持正常操作及查询。\n（1）可以取消CODO认款；\n（2）可以争议，只能全部争议；\n（3）触发审批流程，已清账的需要审批。",
      "fte": "2.7777777777777779E-3",
      "cost": "10000",
      "status": "待审批",
      "type": "CR",
      "step": "05 到账与核销",
      "i": "到款核销",
      "processStep": "到款核销"
    },
    {
      "system": "AR Portal",
      "changePoint": "对接合同folder抓取",
      "remark": "合同扫描件（Phase2）改成从AmandA读水印章文件 - 系统对接实现有难度",
      "fte": "0",
      "cost": "",
      "status": "取消",
      "type": "CR",
      "step": "02 开票与其他支持材料交付",
      "i": "其他资料交付",
      "processStep": "其他资料交付"
    },
    {
      "system": "AR Portal",
      "changePoint": "文件特殊规则配置界面",
      "remark": "KA - 是指需要特殊文件 的配置主要还是提供盖章PO件，分两块：1，需要PO盖章件匹配提供在对应的发票，随数电发票+盖章PO方式发送指定邮箱。2，同 一个PO涉及多个发票或Billing(分批发货这种情况）， 同一盖章PO需要持续覆盖在这个PO不同的Billing或发票维度上。\n1) KA这块如果两点都达到，可save每月3-4H， 注明下：是除罗氏之外的，罗氏的PO是需要手工勾选出当月发货开票在PO上的明细（一般PO上的SKU大于开票SKU）。罗氏现在平均billing个数每月有110-130左右。\n2) 这部分PO的上线功能，仅限于PO与开票相符\n3) 若开票与PO不符，均需要手工将开票的资料在PO上勾选，所以目前能save的工时有限",
      "fte": "1.9444444444444445E-2",
      "cost": "10000",
      "status": "待审批",
      "type": "CR",
      "step": "02 开票与其他支持材料交付",
      "i": "其他资料交付",
      "processStep": "其他资料交付"
    },
    {
      "system": "RPA",
      "changePoint": "对接RPA-Rebilling/VAT ",
      "remark": "1. VAT的对接处理将通过机器人流程自动化（RPA）实施：saving已预估，并与Michael会议讨论 - Pending\n2. Rebilling的对接，由于两边字段不一致，目前无法实现对接。我们将继续关注后续可能的解决方案。 ",
      "fte": "0.2",
      "cost": "10000",
      "status": "待审批",
      "type": "RPA",
      "step": "03 对账与争议处理",
      "i": "争议识别与处理",
      "processStep": "争议识别与处理"
    },
    {
      "system": "AR Portal",
      "changePoint": "催款函申请流程",
      "remark": "\t四级催款函，系统设置模版即可。无需自动发送，由收款员手动转发任务给销售\n1. 收款员可以选择需要发送的Billing，系统自动获取Billing上面的跟进记录\n2. 展示当前BT/Billing对应的销售，允许收款员可以选择其他销售\n3. 生产任务给对应的销售，销售需要在页面点击Approve和Reject。\n-\t如果是Approve，账单就直接推送给客户，CC收款员。\n-\t如果Reject，需要通知收款员。\nNote：四级催款函任务超24小时没有处理，系统发一封邮件提醒销售",
      "fte": "2.5000000000000001E-2",
      "cost": "7500",
      "status": "待审批",
      "type": "CR",
      "step": "04 催收与承诺管理",
      "i": "分级催款",
      "processStep": "分级催款"
    },
    {
      "system": "AR Portal",
      "changePoint": "应收账款升级",
      "remark": "1. 触发：逾期≥60天且违约≥3次/长期失联≥180天/大额且配合低/坏账信号 - 根据规则自动提醒/升级\n2. 提请主管介入，或联合Sales/信控/管理层/法务沟通，明确管理决策 - 自动生成汇报内容并进行升级",
      "fte": "0.01",
      "cost": "10000",
      "status": "待审批",
      "type": "CR",
      "step": "04 催收与承诺管理",
      "i": "升级触发",
      "processStep": "升级触发"
    },
    {
      "system": "AR Portal",
      "changePoint": "签收日期",
      "remark": "AR portal添加送货单上的签收日期",
      "fte": "0.01",
      "cost": "7500",
      "status": "待审批",
      "type": "CR",
      "step": "02 开票与其他支持材料交付",
      "i": "其他资料交付",
      "processStep": "其他资料交付"
    },
    {
      "system": "AR Portal",
      "changePoint": "月结&核对后开票",
      "remark": "关于需客户确认开票，是否可以邮件直接发送客户确认，免于收款员人工整理明细并发送",
      "fte": "0.1",
      "cost": "10000",
      "status": "待审批",
      "type": "CR",
      "step": "02 开票与其他支持材料交付",
      "i": "特殊开票",
      "processStep": "特殊开票"
    },
    {
      "system": "AR Portal",
      "changePoint": "科研平台结算（尤其后补单）",
      "remark": "AR Portal和科研平台明细比对（见三方平台）\n1. 可结算状态，且明细金额一致直接自动申请VAT开票\n2. 不可结算：推动平台订单结算状态（方元平台二维码发送客户收货、库巴扎上传签收单后15天自动验收）\n3. 平台订单状态返还：如有订单状态，如实反馈至AR Portal，如未匹配到订单，返回状态”未补单“至AR Portal\n4. 自动抓取购买人、收货人联系方式",
      "fte": "0",
      "cost": "42500",
      "status": "待审批",
      "type": "CR",
      "step": "02 开票与其他支持材料交付",
      "i": "特殊开票",
      "processStep": "特殊开票"
    },
    {
      "system": "AR Portal",
      "changePoint": "公司客户平台结算",
      "remark": "AR Portal和公司平台明细比对：e.g. 药明、三生、金斯瑞平台，特性是以PO为核准单位（见三方平台）\n1. 进行结算比对\n- PO、数量、金额等关键信息比对完全一致后进行结算并上传发票。\n- 比对不一致，需要返回状态至AR Portal，汇总发送销售一同跟进\n2. 公司多为自建平台，需要沟通RPA、爬虫可能性\n优先度暂缓",
      "fte": "0",
      "cost": "20000",
      "status": "待审批",
      "type": "CR",
      "step": "02 开票与其他支持材料交付",
      "i": "特殊开票",
      "processStep": "特殊开票"
    },
    {
      "system": "Process",
      "changePoint": "收款流程优化",
      "remark": "1. 如果前后台划分会涉及工作时间点集中：月初账单准备、开票；季度底年底集中到款核销\n2. 前后台划分为未来自动化提供基础，但目前纯人工操作可能增加沟通的时间成本\n3. Saving主要体现在表格前述各步骤的机会中\n",
      "fte": "0",
      "cost": "",
      "status": "评估中",
      "type": "CR",
      "step": "02 开票与其他支持材料交付",
      "i": "特殊开票",
      "processStep": "特殊开票"
    },
    {
      "system": "AR Portal",
      "changePoint": " HK Collection整合",
      "remark": "AR Portal (预计saving 0.202）\n1) AR reminder & 发票整理与发送 : 0.040\n2) 对账单 & 催款邮件 ：0.116\n3) P-card 图片信息抓取与整理：0.046\n",
      "fte": "0.18",
      "cost": "40000",
      "status": "待审批",
      "type": "CR",
      "step": "10 其他",
      "i": "流程整合",
      "processStep": "流程整合"
    },
    {
      "system": "AR Portal",
      "changePoint": "AB service 整合进AR Portal",
      "remark": "1. 收款计划管理\n2. 客户对账配置管理，对账文件要求，账单要求，对账要求，提醒设置等(显示对应的维保期间、终端信息、设备序列号、对应的工程师and 销售)\n3. 客户对账单制作和发送,。目前，70%标准对账单(邮件发送平台) ，30%手工处理 非标对账单。未来系统根据客户的要求，自动按要求生成对账单。按照SO发送对账单\n4. 对账文件管理（服务确认单、服务报告、合同等）\n5. 收款跟进状态管理(Billing和发票两个维度)\n6. 对账客户认证和授权\n7.对账人需要纯手工维护，以SO和公司对应",
      "fte": "0.28000000000000003",
      "cost": "47500",
      "status": "待审批",
      "type": "CR",
      "step": "10 其他",
      "i": "流程整合",
      "processStep": "流程整合"
    },
    {
      "system": "Process",
      "changePoint": "AI-Generated Customer Communication Summaries",
      "remark": "Background\nCollectors spend significant time documenting customer calls and updating AR Portal manually\nAverage call documentation takes 5–10 minutes per interaction, reducing productive collection time by ~20%\nInconsistent note-taking leads to incomplete records, making it difficult to track dispute context and payment commitments\n\nSolution\nDeploy AI-powered speech-to-text to automatically transcribe customer calls and voice conversations in real time\nUse NLP models to extract key information and generate structured summaries\nAuto-populate AR Portal fields directly from the generated summary\n\nBenefit\nReduce manual documentation effort by an estimated 30–40%, freeing collectors to focus on high-value negotiations\nImprove record consistency and completeness across all customer interactions for better audit trails\nStrengthen collection visibility with searchable, structured call histories enabling faster handoffs and dispute resolution",
      "fte": "1",
      "cost": "",
      "status": "评估中",
      "type": "AI",
      "step": "04 催收与承诺管理",
      "i": "高频客户跟进",
      "processStep": "高频客户跟进"
    },
    {
      "system": "New",
      "changePoint": "AI-Assisted for Customer and Invoice Change Requests",
      "remark": "Background\nCustomer information changes and invoice rule updates are submitted through fragmented manual channels\nSales and collections teams spend ~20% of processing time re-keying and verifying change request data across systems\nLack of standardized intake leads to frequent handoff errors, duplicate submissions, and delayed processing\nSolution\nCreate a guided app for sales submission with structured input fields and validation rules for customer change requests\nDeploy AI-assisted extraction and classification to automatically parse change request details from unstructured inputs\nRoute classified requests to appropriate approval workflows with pre-populated data, reducing manual touchpoints\nBenefit\nImprove data input quality and first-time accuracy, reducing downstream rework by an estimated 30–40%\nReduce handoff errors between sales and collections through standardized, validated submission workflows\nAccelerate change request processing cycle from 3–5 days to <1 day for standard requests",
      "fte": "0.01",
      "cost": "0",
      "status": "待审批",
      "type": "AI",
      "step": "02 开票与其他支持材料交付",
      "i": "特殊开票",
      "processStep": "特殊开票"
    }
  ]
};
